apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-app
  template:
    metadata:
      labels:
        app: music-app
    spec:
      containers:
      - name: music-app
        image: vamsichamarthi/musicappimage:IMAGE_TAG
        ports:
        - containerPort: 80
